#!/bin/bash
set -e

# This script runs once as the postgres user during database initialization.

# 1. Create a subdirectory for WAL files inside the main data volume.
# This avoids host permission issues, especially in rootless Docker environments.
mkdir -p /var/lib/postgresql/data/wal-archive

# 2. Append replication rules to the default pg_hba.conf generated by initdb.
echo "host replication admin 0.0.0.0/0 md5" >> "$PGDATA/pg_hba.conf"
echo "host all all 0.0.0.0/0 md5" >> "$PGDATA/pg_hba.conf"

# 3. Append necessary parameters to the default postgresql.conf.
cat >> "$PGDATA/postgresql.conf" <<EOF
wal_level = replica
archive_mode = on
archive_command = 'cp %p /var/lib/postgresql/data/wal-archive/%f'
max_wal_senders = 10
hot_standby = on
EOF

echo "Initialization complete: pg_hba.conf and postgresql.conf configured for replication."